### ISSUE TITLE
TCR prediction or annotation

### ISSUE THREAD

**Issue by mainharryHR** [ncborcherding/Trex#15]
Dear Nick,

Thank you for the great package. After TCR annotation, how should we interpret the data. Here comes two typical output. I wanna categorize the antigen epitopes. For some of them (see following), there are many predictions, I am wondering if the first prediction (Brain Cancer), is the highest possibility and SelgAg is the lowest possibilities. 

I also feel it might be related to the Alphabet, But the second lines does not fit this rules, Cause "Brain Cancer" is at the end.
`Brain Cancer;Celiac disease;CMV;Diabetes Type 1;Rasmussen encephalitis;SelfAg`
`Allergy;CMV;Influenza;M.tuberculosis;Rasmussen encephalitis;SelfAg;Brain Cancer`

Any comments are welcome.

Thank you.

Have a nice day!

Best,
Hairu

**Comment by ncborcherding** [comment]
Hey Hairu, 

I am working on a method for prioritizing antigen/tcr annotation and/or prediction. But right now ```annotateDB()``` is just a database search using the cdr3 sequence. It should be reported in alphabetical order - there must be an issue with the consolidation step in the database.

Nick
