### ISSUE TITLE
maTrex encoder.input = "both" options does not work

### ISSUE THREAD

**Issue by Lucyyang1991** [ncborcherding/Trex#21]
I really want to use the "both" option, and I guess there was a bug in the code, which is the `.encoder` function wrongly wrote the "both" with " both", the difference is there is a space before "both". Hoping for the "both" option coming back.
![微信截图_20241104171004](https://github.com/user-attachments/assets/54a2f52b-6513-4095-9494-a10c4e396f61)

**Comment by ncborcherding** [comment]
Hey Lucy, 

I am in the process of updating Trex for increased compatibility and more models - getting it prepperd for bioconductor submission. I dropped "both" model from the most recent version. You can install an old commit of Trex that will allow you to use "both".

Thanks,
Nick
