### ISSUE TITLE
How to interpret the Trex result?

### ISSUE THREAD

**Issue by Lucyyang1991** [ncborcherding/Trex#22]
Thanks for the effort to develop this package! After runing Trex with TCR alpha and beta chain, I integrate them with RNA result. Finally I got a wnn UMAP, I'm just wondering can I assume that the TCR sequence of the same wnn subgroup can recognize the same epitope? How can I prove that? Or do you have any more offical interpretation of the result?
```
sc <- runTrex(
  sc,
  chains = "TRA",
  encoder.model = "VAE",
  encoder.input = "both", #error
  reduction.name = "TRA.both"
) # take long time

sc <- runTrex(
  sc,
  chains = "TRB",
  encoder.model = "VAE",
  encoder.input = "both",
  reduction.name = "TRB.both"

sc <- FindMultiModalNeighbors(
  sc,
  reduction.list = list("pca", "TRA.both", "TRB.both"),
  dims.list = list(1:30, 1:10, 1:10),
  modality.weight.name = "RNA.weight"
)

sc <- RunUMAP(
  sc,
  nn.name = "weighted.nn",
  reduction.name = "wnn.umap",
  reduction.key = "wnnUMAP_"
)

sc <- FindClusters(
  sc,
  graph.name = "wsnn",
  resolution = seq(.1, 1, .1),
  algorithm = 3,
  verbose = FALSE
)
```

**Comment by ncborcherding** [comment]
Hey @Lucyyang1991, 

Good question - I am not sure you can say that the closely related cells from the trimodal embedding are truly "epitope-specific" without showing possibly previously established epitope mapping (like using VDJdb or ```annotateDB()```) or actual in vitro work. 

In our [own work](https://www.nature.com/articles/s41590-024-01888-9), we found that although closely related in terms of position and clustering, the clones we infered spike antigen specificity mapped to different epitopes along the spike protein. I think this makes sense as we are including RNA into the reduction, so you are getting a "reactive" expression profile. 
<img width="495" alt="Screenshot 2024-11-06 at 11 52 06 AM" src="https://github.com/user-attachments/assets/a27c00ce-30f9-474a-9a9b-d9e24cfca758">

We are working on some newer models for true "epitope" specificity - so watch this space, but for now, I think "antigen" or "reactive" might be better terms. 

Nick
