### ISSUE TITLE
Issues with maTrex function

### ISSUE THREAD

**Issue by kromine1130** [ncborcherding/Trex#4]
Hello,
I am running the following line: 
```
Trex_vectors <- maTrex(my_trex, 
                       chains = "TRB",
                       AA.properties = "both")
```
and getting:
 ```
Error in str_split(sub$genes, "[.]", simplify = TRUE)[, 2] : 
  subscript out of bounds
```

I also get this error with: 

```
my_trex <- runTrex(my_trex, 
                     chains = "TRB",
                     AA.properties = "KF", 
                     reduction.name = "Trex.KF")
```

the my_trex object was generated by taking my output from scRepertoire(), which worked great, and running the combineTCR() function with my seurat object. I do not run into any issues at this step and can do downstream analyses such as clonalNetworks(), etc. It is unclear from the source code how I could be getting this error. This is on version 0.99.6. Any advice would be much appreciated!

**Comment by ncborcherding** [comment]
Hey Kyle, 

So what is going on here is there was not support of lists for either ```maTrex()``` or ```runTrex()``` - both assumed the use of single-cell objects. In the new dev version (v0.99.9) ```maTrex()``` now supports the use of the direct output from ```combineTCR()``` from scRepertoire. Because ```runTrex()``` filters and ammends a single-cell object with the encoded values, for now it will not support the same list. 

Hope that helps and let me know if you have any issues/suggestions. 

Nick

**Comment by kromine1130** [comment]
Sorry I must have misunderstood the code. This IS on a combined seurat object, which I created with 
```
my_trex <- combineExpression(combined, 
                                   my_trex, 
                                   cloneCall="gene", 
                                   group.by = "sample", 
                                   proportion = FALSE, 
                                   cloneTypes=c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))
```

Where my_trex is my single-cell seurat object containing T cells and matching barcodes. If I run: 
```
my_trex <- runTrex(my_trex, 
                        chains = "TRB",
                        AA.properties = "KF", 
                        reduction.name = "Trex.KF")
```
I get the same error code

**Comment by ncborcherding** [comment]
Hey Kyle, 

Sorry about the confusion (but even if that wasn't your issue, it was a good suggestion). 

It looks like the error is stemming from an internal function called ```getTCR()```, specifically as part of pulling all of the TCR contig information from the single-cell object, it separates out the v and j genes using the ```str_split(sub$genes, "[.]", simplify = TRUE)[, 2]```

Do you see any issues with the "CTgene" variable in the meta data? Can you run the following without errors?
```
TRB.genes <- stringr::str_split(my_trex$CTgene, [.]", simplify = TRUE)[, 2]
j.TRB.genes <- str_split(TRB.genes, "[.]", simplify = TRUE)[, 2]
```

Alternatively, if this does not work - would you mind [emailing](mailto:ncborch@gmail.com) your meta data so I can track down the issue? Thanks for bearing with me on all the troubleshooting as of late. 

Nick

**Comment by kromine1130** [comment]
Sounds good, sent over the metadata as I am still running into issues with the line above

**Comment by ncborcherding** [comment]
Hey Kyle, 

Think I managed to track down the issue you have and it is in fact, scRepertoire's fault - 
<img width="432" alt="Screen Shot 2023-01-27 at 10 36 58 AM" src="https://user-images.githubusercontent.com/22754118/215142208-af14c820-f523-4f32-914a-89971664b317.png">

There was a persistent issue in the ```parseWAT3R()``` internal function that led to an error in TRB and TRA chains being placed in the same position along both the "CTaa" and "CTgene" variables (usually the chains are separated by "_"). The error you were getting was the result of not having any TCRB chains to parse (in the correct position at least). I will commit an update to scRepertoire this morning that fixes this issue.

The other thing I would mention from looking at the meta data is that as of right now, there is no handling of the barcodes with multiple alpha or beta chains. When using scRepertoire's ```combineTCR()``` I would recommend using  **filterMulti** = TRUE

Thanks for all the help with the troubleshooting. 

Nick

**Comment by zthoms** [comment]
Running into a similar issue here. When I run: 

```
so <- runTrex(so, 
            chains = "TRB",
            encoder.model = "VAE", 
            encoder.input = "KF",
            reduction.name = "Trex.KF")
```
I get this error: 
```
Error in str_split(sub$genes, "[.]", simplify = TRUE)[, 2]: subscript out of bounds
Traceback:

1. maTrex(sc = sc, chains = chains, method = method, encoder.model = encoder.model, 
 .     encoder.input = encoder.input, theta = theta)
2. getTCR(sc, chains)
```

However, I'm able to run this suggested code without any issues: 
```
TRB.genes <- stringr::str_split(combined.TCR[[1]]$CTgene, "_", simplify = TRUE)[, 2]
j.TRB.genes <- stringr::str_split(TRB.genes, "[.]", simplify = TRUE)[, 2]
```
Upstream of this I'm running MiXCR for TCR alignment. Any suggestions on troubleshooting this? Thanks!

**Comment by ncborcherding** [comment]
@zthoms 

Can you give more information about your preprocessing? Is so a single-cell object that has sequences attached by scRepertoire?

Nick

**Comment by zthoms** [comment]
Yes, "so" here is a Seurat Object. Preprocessing workflow was: 

- Created a merged Seurat object from 16 samples
- Read in clones via scRepertoire "loadContigs"
- Ran combineTCR w/ filterMulti = TRUE (ends up being a list of 16 dataframes)
- Ran combineExpression:
```
so <- combineExpression(combined.TCR, 
                         so, 
                         cloneCall="gene", 
                         group.by = "sample", 
                         proportion = TRUE)
```

**Comment by ncborcherding** [comment]
Hey @zthoms, 

Apologies for the delay due to the holiday weekend, could you make a reproducible example? I can not do much with not with the listed workflow. 

Thanks,
Nick
