### ISSUE TITLE
Confusion about Trex aplication

### ISSUE THREAD

**Issue by beginner984** [ncborcherding/Trex#6]
Sorry for this stupid question

After a nightmare of tensorflow installation, I run Trex on my seurat+TCR data

Looking at the results, if I am not wrong, only TCRs having an epitope known in public databases returned

![Rplot](https://github.com/ncborcherding/Trex/assets/43682980/a080595a-afa5-4a50-8329-fc20bb9677ae)

So, does Trex do any prediction for possible novel TCRs?

Thanks for developing that

**Comment by ncborcherding** [comment]
Hey @beginner984,

Sorry about the tensorflow issue - trying to update to be compatible with more versions.

Trex does not yet do predictions in a formal sense, only adding annotations by edit distance. However, using this approach, you can look at the neighbors and possibly infer annotation (This is what the submitted Trex publication is all about). I am hoping to add more functionality to this in the future though so there will be a more formal prediction with a confidence interval.

Nick
